apiVersion: v1
kind: Pod
metadata:
  name: oreilly
  labels:
    name: oreillyapp
spec:
  containers:
  - name: oreillycontainer
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
